from typing import Protocol, runtime_checkable


@runtime_checkable
class Writable(Protocol):
    def write(self, text: str, /) -> int: ...
    def flush(self) -> None: ...


@runtime_checkable
class TerminalWritable(Protocol):
    def write(self, text: str, /) -> int: ...
    def flush(self) -> None: ...
    def isatty(self) -> bool: ...
