clone:
  git:
    image: woodpeckerci/plugin-git
    settings:
      depth: 1
      recursive: false
      lfs: false

steps:
  build-and-publish:
    image: astral/uv:bookworm-slim
    environment:
      UV_PUBLISH_URL: https://upload.pypi.org/legacy/
      UV_PUBLISH_TOKEN:
        from_secret: pypi-publish
    commands:
      - uv build --wheel
      - uv publish
    when:
      event: release
    depends_on: []

when:
  branch: main
  event: release
